name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/labo:latest .
        docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/labo:latest
    
    - name: Scan for vulnerabilities
      run: |
        docker run --rm -v $PWD:/work -w /work aquasec/trivy --severity HIGH,CRITICAL -o trivy_report.json docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/labo:latest

    - name: Upload Trivy report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy_report.json
